apiVersion: v2
name: zea-opc-b03-digital-kyc-vanushree
description: Helm chart for digital kyc verification tracker system by vanushree
version: 1.0.0-SNAPSHOT
appVersion: "0.0.1"
dependencies:
  - name: common
    version: 1.0.98
    repository: '@chartrepo'
